[package]
name = "local-web-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", features = ["default"] }
bytes = { version = "1" }
log = "0.4"
pretty_env_logger = "0.5.0"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4.3"
